# Generated by Django 4.2.4 on 2023-08-10 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 14, 34, 39, 393460), null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 14, 34, 39, 393460), null=True),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 14, 34, 39, 393460), null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 14, 34, 39, 393460), null=True),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestions',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 14, 34, 39, 393460), null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 14, 34, 39, 393460), null=True),
        ),
        migrations.AlterField(
            model_name='listfield',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 14, 34, 39, 393460), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 14, 34, 39, 393460), null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 14, 34, 39, 393460), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 14, 34, 39, 393460), null=True),
        ),
    ]
